language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "b6u5rejenxudr8yva"
    token:
      secure: "e304a922c7eef972aded8d0e0c89cbd448e038f4"
jdk:
  - oraclejdk8
script:
  - ./gradlew clean test sonarqube
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'
